export const UPDATE_CURRENT_WEATHER_DATA = 'UPDATE_CURRENT_WEATHER_DATA';

export const CURRENT_WEATHER_DATA_RESULT = 'CURRENT_WEATHER_DATA_RESULT';
export const CURRENT_WEATHER_DATA_ERROR = 'CURRENT_WEATHER_DATA_ERROR';


export const updateCurrentWeather = () => ({
    type: UPDATE_CURRENT_WEATHER_DATA,
});